export interface MajorOption {
  value: string;
  label: string;
}

export const majors: MajorOption[] = [
  { value: "accounting", label: "Accounting" },
  { value: "accounting-and-analytics", label: "Accounting and Analytics" },
  { value: "actuarial-science", label: "Actuarial Science" },
  { value: "american-studies", label: "American Studies" },
  { value: "animation", label: "Animation" },
  { value: "animation-and-games", label: "Animation and Games" },
  { value: "applied-cognition-and-neuroscience", label: "Applied Cognition and Neuroscience" },
  { value: "applied-sociology", label: "Applied Sociology" },
  { value: "art-history", label: "Art History" },
  { value: "artificial-intelligence-for-biomedical-sciences", label: "Artificial Intelligence for Biomedical Sciences" },
  { value: "arts-technology-and-emerging-communication", label: "Arts, Technology, and Emerging Communication" },
  { value: "audiology", label: "Audiology" },
  { value: "biochemistry", label: "Biochemistry" },
  { value: "bioinformatics-and-computational-biology", label: "Bioinformatics and Computational Biology" },
  { value: "biology", label: "Biology" },
  { value: "biomedical-engineering", label: "Biomedical Engineering" },
  { value: "biomedical-sciences", label: "Biomedical Sciences" },
  { value: "biotechnology", label: "Biotechnology" },
  { value: "business-administration", label: "Business Administration" },
  { value: "business-analytics-and-artificial-intelligence", label: "Business Analytics and Artificial Intelligence" },
  { value: "chemistry", label: "Chemistry" },
  { value: "child-learning-and-development", label: "Child Learning and Development" },
  { value: "cognition-and-neuroscience", label: "Cognition and Neuroscience" },
  { value: "cognitive-science", label: "Cognitive Science" },
  { value: "computational-and-geospatial-science", label: "Computational and Geospatial Science" },
  { value: "computer-engineering", label: "Computer Engineering" },
  { value: "computer-information-systems-and-technology", label: "Computer Information Systems and Technology" },
  { value: "computer-science", label: "Computer Science" },
  { value: "criminology", label: "Criminology" },
  { value: "cyber-security-technology-and-policy", label: "Cyber Security, Technology, and Policy" },
  { value: "cybersecurity-and-risk-management", label: "Cybersecurity and Risk Management" },
  { value: "cybersecurity-technology-and-policy", label: "Cybersecurity Technology and Policy" },
  { value: "data-science", label: "Data Science" },
  { value: "data-science-and-statistics", label: "Data Science and Statistics" },
  { value: "economics", label: "Economics" },
  { value: "education", label: "Education" },
  { value: "electrical-engineering", label: "Electrical Engineering" },
  { value: "energy-management", label: "Energy Management" },
  { value: "engineering", label: "Engineering" },
  { value: "finance", label: "Finance" },
  { value: "financial-technology-and-analytics", label: "Financial Technology and Analytics" },
  { value: "game-development", label: "Game Development" },
  { value: "geosciences", label: "Geosciences" },
  { value: "geospatial-information-sciences", label: "Geospatial Information Sciences" },
  { value: "global-business", label: "Global Business" },
  { value: "healthcare-administration-and-leadership", label: "Healthcare Administration and Leadership" },
  { value: "healthcare-leadership-and-management", label: "Healthcare Leadership and Management" },
  { value: "healthcare-management", label: "Healthcare Management" },
  { value: "healthcare-studies", label: "Healthcare Studies" },
  { value: "history", label: "History" },
  { value: "human-development-and-early-childhood-disorders", label: "Human Development and Early Childhood Disorders" },
  { value: "human-resource-management", label: "Human Resource Management" },
  { value: "humanities", label: "Humanities" },
  { value: "information-technology-and-management", label: "Information Technology and Management" },
  { value: "innovation-and-entrepreneurship", label: "Innovation and Entrepreneurship" },
  { value: "interdisciplinary-studies", label: "Interdisciplinary Studies" },
  { value: "international-management-studies", label: "International Management Studies" },
  { value: "international-political-economy", label: "International Political Economy" },
  { value: "latin-american-studies", label: "Latin American Studies" },
  { value: "leadership-and-organizational-development", label: "Leadership and Organizational Development" },
  { value: "literature", label: "Literature" },
  { value: "management-science", label: "Management Science" },
  { value: "marketing", label: "Marketing" },
  { value: "materials-science-and-engineering", label: "Materials Science and Engineering" },
  { value: "mathematics", label: "Mathematics" },
  { value: "mathematics-education", label: "Mathematics Education" },
  { value: "mechanical-engineering", label: "Mechanical Engineering" },
  { value: "media-arts-and-design", label: "Media Arts and Design" },
  { value: "molecular-and-cell-biology", label: "Molecular and Cell Biology" },
  { value: "molecular-biology", label: "Molecular Biology" },
  { value: "neuroscience", label: "Neuroscience" },
  { value: "philosophy", label: "Philosophy" },
  { value: "physics", label: "Physics" },
  { value: "political-science", label: "Political Science" },
  { value: "professional-communication-and-digital-media-studies", label: "Professional Communication and Digital Media Studies" },
  { value: "psychology", label: "Psychology" },
  { value: "public-affairs", label: "Public Affairs" },
  { value: "public-health", label: "Public Health" },
  { value: "public-policy", label: "Public Policy" },
  { value: "public-policy-and-political-economy", label: "Public Policy and Political Economy" },
  { value: "science-education", label: "Science Education" },
  { value: "social-data-analytics-and-research", label: "Social Data Analytics and Research" },
  { value: "sociology", label: "Sociology" },
  { value: "software-engineering", label: "Software Engineering" },
  { value: "speech-language-and-hearing-sciences", label: "Speech, Language, and Hearing Sciences" },
  { value: "speech-language-pathology", label: "Speech-Language Pathology" },
  { value: "supply-chain-management", label: "Supply Chain Management" },
  { value: "supply-chain-management-and-analytics", label: "Supply Chain Management and Analytics" },
  { value: "sustainability-planning-and-policy", label: "Sustainability Planning and Policy" },
  { value: "systems-engineering", label: "Systems Engineering" },
  { value: "systems-engineering-and-management", label: "Systems Engineering and Management" },
  { value: "visual-and-performing-arts", label: "Visual and Performing Arts" },
];
