export interface MajorOption {
  value: string;
  label: string;
}

export const majors: MajorOption[] = [
  { value: "biomedical-engineering", label: "Biomedical Engineering" },
  { value: "computer-engineering", label: "Computer Engineering" },
  { value: "computer-science", label: "Computer Science" },
  { value: "data-science", label: "Data Science" },
  { value: "electrical-engineering", label: "Electrical Engineering" },
  { value: "mechanical-engineering", label: "Mechanical Engineering" },
  { value: "software-engineering", label: "Software Engineering" },
  { value: "accounting", label: "Accounting" },
  { value: "business-administration", label: "Business Administration" },
  { value: "business-analytics", label: "Business Analytics" },
  { value: "finance", label: "Finance" },
  { value: "global-business", label: "Global Business" },
  { value: "healthcare-management", label: "Healthcare Management" },
  { value: "human-resource-management", label: "Human Resource Management" },
  { value: "information-technology-systems", label: "Information Technology and Systems" },
  { value: "marketing", label: "Marketing" },
  { value: "supply-chain-management", label: "Supply Chain Management" },
  { value: "animation-games", label: "Animation and Games" },
  { value: "arts-technology-emerging-communication", label: "Arts, Technology, and Emerging Communication (ATEC)" },
  { value: "art-history", label: "Art History" },
  { value: "history", label: "History" },
  { value: "interdisciplinary-studies", label: "Interdisciplinary Studies" },
  { value: "literature", label: "Literature" },
  { value: "philosophy", label: "Philosophy" },
  { value: "visual-performing-arts", label: "Visual and Performing Arts" },
  { value: "child-learning-development", label: "Child Learning and Development" },
  { value: "cognitive-science", label: "Cognitive Science" },
  { value: "neuroscience", label: "Neuroscience" },
  { value: "psychology", label: "Psychology" },
  { value: "speech-language-hearing", label: "Speech, Language, and Hearing Sciences" },
  { value: "criminology-criminal-justice", label: "Criminology and Criminal Justice" },
  { value: "economics", label: "Economics" },
  { value: "geospatial-information-sciences", label: "Geospatial Information Sciences" },
  { value: "international-political-economy", label: "International Political Economy" },
  { value: "political-science", label: "Political Science" },
  { value: "public-affairs", label: "Public Affairs" },
  { value: "public-policy", label: "Public Policy" },
  { value: "sociology", label: "Sociology" },
  { value: "actuarial-science", label: "Actuarial Science" },
  { value: "biochemistry", label: "Biochemistry" },
  { value: "biology", label: "Biology" },
  { value: "chemistry", label: "Chemistry" },
  { value: "geosciences", label: "Geosciences" },
  { value: "mathematics", label: "Mathematics" },
  { value: "molecular-biology", label: "Molecular Biology" },
  { value: "physics", label: "Physics" },
];
